---
# refresh fact cache of all servers
- hosts: all
  gather_facts: True

- hosts: servers
  roles:
    - common

- hosts: lxd_hosts
  roles:
    - lxd_host
    - role: users
      tags: users
      groups_for_roles:
        - role: admin
          groups: sudo,adm,lxd

- hosts: dub-registry.ci.lxd
  vars:
    - dub_registry_http_port: 8080
  roles:
    - dub_registry_mirror

- hosts: jenkins.ci.lxd
  vars:
    - jenkins_url: https://ci.dlang.io/
    - jenkins_http_port: 8080
    - jenkins_slave_agent_port: 55000
    - jenkins_admin_username: MartinNowak
    - jenkins_github_organizations: [dlang]
  vars_files:
    - vars/passwords.yml # jenkins_admin_password
  roles:
    - jenkins
  tasks:
    - name: tools
      apt: { name: "{{ item }}", install_recommends: no, update_cache: yes, cache_valid_time: 3600 }
      with_items: [git, jq]
    - block:
      - name: download gcloud sdk
        unarchive:
          src: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-183.0.0-linux-x86_64.tar.gz
          dest: $HOME/
          remote_src: yes
      - name: copy service account credentials
        copy: { src: dlang-ci 2ad4426ddfa9.json, dest: /var/lib/jenkins/google-cloud-sdk/dlang-ci 2ad4426ddfa9.json, mode: 0400, owner: jenkins, group: jenkins }
        become_user: root
      - name: activate service account
        command: $HOME/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file='$HOME/google-cloud-sdk/dlang-ci 2ad4426ddfa9.json'
      - name: configure default project
        command: $HOME/google-cloud-sdk/bin/gcloud config set project dlang-ci
      become_user: jenkins
      tags: gcloud-sdk
    # https://cloud.google.com/compute/docs/faq#networking
    - name: get dns entries to query for GCE netblocks
      set_fact:
        gce_netblocks: "{{ lookup('dig', '_cloud-netblocks.googleusercontent.com', 'qtype=TXT') | regex_findall('include:([^ ]+)', '\\1') }}"
    - name: get cloud netblocks
      set_fact:
        tmp: "{{ lookup('dig', item, 'qtype=TXT') | regex_findall('ip4:([^ ]+)', '\\1') }}"
      with_items: "{{ gce_netblocks }}"
      register: gce_netblocks
    - name: extract netblocks
      set_fact:
        gce_netblocks: "{{ gce_netblocks.results | sum(attribute='ansible_facts.tmp', start=[]) }}"

    - name: reset to default firewall setup
      include: roles/common/tasks/firewall.yml
    - name: allow http reverse proxy
      ufw: { rule: allow, src: "{{ item }}", port: "{{ jenkins_http_port }}", proto: tcp }
      with_items:
        - "{{ hostvars['ci.dlang.io'].ansible_lxdbr0.ipv4.address }}"
        - "{{ hostvars['ci.dlang.io'].ansible_lxdbr0.ipv6[0].address }}"
    - name: allow agent traffic
      ufw: { rule: allow, src: "{{ item }}", port: "{{ jenkins_slave_agent_port }}", proto: tcp }
      with_flattened:
        - "{{ gce_netblocks }}"
        # allow access from host (indirectly SNAT) and directly from other containers
        - ["{{ hostvars['ci.dlang.io'].ansible_default_ipv4.address }}", "{{ ansible_default_ipv4.address }}/24"]
    - name: enable ufw
      ufw: { state: enabled }

- hosts: ci.dlang.io
  tasks:
    - name: forward jenkins agent port
      include: tasks/forward_lxc_port.yml
      vars:
        protocol: tcp
        host_ip: "{{ ansible_default_ipv4.address }}"
        host_port: 55000
        container_ip: "{{ hostvars['jenkins.ci.lxd'].ansible_default_ipv4.address }}"
        container_subnet: "{{ hostvars['jenkins.ci.lxd'].ansible_default_ipv4.address }}/24"
        container_port: 55000
  handlers:
    - name: save iptables
      shell: >
        iptables-save > /etc/iptables/rules.v4;
        ip6tables-save > /etc/iptables/rules.v6

- hosts: jenkins_slaves
  vars:
    - jenkins_url: https://ci.dlang.io/
    - jenkins_admin_username: MartinNowak
  vars_files:
    - vars/passwords.yml # jenkins_admin_password
  roles:
    - jenkins_slave

- hosts: buildkite_agents
  vars_files:
    - vars/passwords.yml # buildkite_agent_token
  roles:
    - buildkite_agent

- hosts: jenkins_slaves,buildkite_agents
  tasks:
    - name: test dependencies (1/2)
      apt: { name: "{{ item }}", install_recommends: no, update_cache: yes, cache_valid_time: 3600 }
      with_items:
        - build-essential
        - curl
        - gdb
        - git
        - jq
        - libblas-dev
        - libbz2-dev
        - libcairo-dev
        - libclang-4.0-dev # dstep
        - libcurl4-gnutls-dev
        - libevent-dev
        - libgcrypt20-dev
        - libgpg-error-dev
        - libgtk-3-0
        - liblapack-dev
        - liblzo2-dev
        - libopenblas-dev
        - libreadline-dev
        - libssl-dev
        - libxml2-dev
        - libxslt1-dev
        - libzmq3-dev
        - mongodb-server
        - moreutils # sponge et.al.
        - pkg-config
        - python-dev
        - python-yaml
        - python3-nose
        - redis-server
        - rsync
        - unzip
      tags: deps
    - name: test dependencies (2/2)
      apt: { deb: "{{ item }}", install_recommends: no }
      with_items:
        - https://bintray.com/sociomantic-tsunami/dlang/download_file?file_path=libebtree6_6.0.s7-rc5-xenial_amd64.deb
        - https://bintray.com/sociomantic-tsunami/dlang/download_file?file_path=libebtree6-dev_6.0.s7-rc5-xenial_amd64.deb
        - https://bintray.com/sociomantic-tsunami/dlang/download_file?file_path=d1to2fix_0.10.0-alpha1-xenial_amd64.deb
      tags: deps
    - name: disable mongodb journaling
      lineinfile: { dest: /etc/mongodb.conf, regexp: "^{{ item.key }} *=", line: "{{ item.key }} = {{ item.value }}" }
      with_dict:
        journal: 'false'
        nojournal: 'true'
      notify: restart mongodb
    - name: use ld.gold
      alternatives: { name: ld, link: /usr/bin/ld, path: /usr/bin/ld.gold }
    - name: add load_travis_script command
      copy:
        dest: /usr/local/bin/get_travis_test_script
        mode: 0555
        content: |
          #!/usr/bin/env python
          import sys, yaml

          script = yaml.load(open('.travis.yml', 'r')).get('script', '')
          if isinstance(script, list):
            script = '\n'.join(script)
          print(script)
  handlers:
    - name: restart mongodb
      service: { name: mongodb, state: restarted }

- hosts: ci.dlang.io
  roles:
    - role: haproxy
      tags: haproxy
      backends:
        ci.dlang.io: |
          mode http
          server s1 jenkins.ci.lxd:8080
        code-mirror.dlang.io: |
          mode http
          server s1 dub-registry.ci.lxd:8005
